### ISSUE TITLE
Reproduce the reported results of LLMs

### ISSUE THREAD

**Issue by PINE4PPLE** [zhudotexe/fanoutqa#2]
I want to reproduce the resulits reported in the paper, but the prompts are missing in the paper. Would you provide the prompts or the python scripts to reproduce the reuslts?

**Comment by zhudotexe** [comment]
Sure - the code is kind of messy but I've uploaded it as a reference implementation in  https://github.com/zhudotexe/fanoutqa/commit/fd62fe2b47d5ae308a9119c46676f2e47d494922.
